aksClusterConfig:
  azureCredentialSecret: ""
  dnsPrefix: ""
  dnsServiceIp: 10.0.0.10
  dockerBridgeCidr: 172.17.0.1/16
  kubernetesVersion: 1.29.7
  linuxAdminUsername: azureuser
  loadBalancerSku: Standard
  networkPlugin: kubenet
  nodePools:
  - availabilityZones:
    - "1"
    - "2"
    - "3"
    enableAutoScaling: false
    maxPods: 110
    mode: System
    name: agentpool
    nodeCount: 1
    osDiskSizeGB: 128
    osDiskType: Managed
    osType: Linux
    vmSize: Standard_DS2_v2
  privateCluster: false
  resourceGroup: ""
  resourceLocation: centralindia
  serviceCidr: 10.0.0.0/16
aliClusterConfig:
  addons:
  - name: terway-eniip
  alibabaCredentialSecret: null
  clusterName: hosted-test-cluster
  clusterType: ManagedKubernetes
  endpointPublicAccess: true
  imported: false
  kubernetesVersion: 
  name: hosted-test-cluster
  nodePools:
  - dataDisks:
    - category: cloud_essd
      encrypted: "false"
      size: 40
    desiredSize: 2
    imageId: aliyun_3_x64_20G_alibase_20241218.vhd
    imageType: AliyunLinux3
    instanceTypes:
    - ecs.c7.xlarge
    - ecs.c7a.xlarge
    name: hosted-np1
    runtime: containerd
    runtimeVersion: 1.6.38
    systemDiskCategory: cloud_essd
    systemDiskSize: 20
  proxyMode: ipvs
  regionID: us-east-1
  serviceCIDR: 192.168.0.0/16
  snatEntry: true
  zoneIDs:
  - us-east-1a
  - us-east-1b
awsCredentials: null
azureCredentials:
  environment: AzurePublicCloud
eksClusterConfig:
  kmsKey: ""
  kubernetesVersion: "1.29"
  loggingTypes: []
  nodeGroups:
  - desiredSize: 1
    diskSize: 20
    ec2SshKey: ""
    gpu: false
    imageId: ""
    instanceType: t3.large
    labels: {}
    maxSize: 1
    minSize: 1
    nodeRole: ""
    nodegroupName: ng
    requestSpotInstances: false
    resourceTags: {}
    spotInstanceTypes: []
    subnets: []
    tags: {}
    userData: ""
  privateAccess: false
  publicAccess: true
  publicAccessSources: []
  region: ap-south-1
  secretsEncryption: false
  securityGroups: []
  serviceRole: ""
  subnets: []
  tags: {}
gkeClusterConfig:
  autopilotConfig:
    enabled: false
  clusterAddons:
    horizontalPodAutoscaling: true
    httpLoadBalancing: true
    networkPolicyConfig: false
  clusterIpv4Cidr: ""
  enableKubernetesAlpha: false
  ipAllocationPolicy:
    clusterIpv4CidrBlock: ""
    clusterSecondaryRangeName: ""
    createSubnetwork: false
    nodeIpv4CidrBlock: ""
    servicesIpv4CidrBlock: ""
    servicesSecondaryRangeName: ""
    subnetworkName: ""
    useIpAliases: true
  kubernetesVersion: 1.29.8-gke.1211000
  labels: {}
  locations: []
  loggingService: logging.googleapis.com/kubernetes
  maintenanceWindow: ""
  masterAuthorizedNetworks:
    cidrBlocks: []
    enabled: false
  monitoringService: monitoring.googleapis.com/kubernetes
  network: hosted-providers-ci
  networkPolicyEnabled: false
  nodePools:
  - autoscaling:
      enabled: false
      maxNodeCount: 0
      minNodeCount: 0
    config:
      diskSizeGb: 50
      diskType: pd-standard
      imageType: COS_CONTAINERD
      labels: {}
      localSsdCount: 0
      machineType: n1-standard-2
      oauthScopes:
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
      - https://www.googleapis.com/auth/trace.append
      preemptible: false
      tags: []
      taints: []
    initialNodeCount: 1
    management:
      autoRepair: true
      autoUpgrade: true
    maxPodsConstraint: 110
    name: np
    version: 1.29.8-gke.1211000
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: false
    masterIpv4CidrBlock: ""
  region: ""
  subnetwork: hosted-providers-ci
  zone: asia-south2-c
googleCredentials:
rancher:
  cleanup: false
  insecure: true